AddModelVirtualAttributeCheck: { }
AlwaysAddDbIndexCheck: { }
#CheckSaveReturnValueCheck: { }
#CheckDestroyReturnValueCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
IsolateSeedDataCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
LawOfDemeterCheck: {
  except_methods: [],
  ignored_files: []
}
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
MoveModelLogicIntoModelCheck: { use_count: 4 }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
OveruseRouteCustomizationsCheck: { customize_count: 3 }
ProtectMassAssignmentCheck: {
  except_methods: [],
  ignored_files: []
}
RemoveEmptyHelpersCheck: {
  ignored_files: ["user_helper.rb"
  ]
}
#RemoveTabCheck: { }
RemoveTrailingWhitespaceCheck: { }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: ["StaticPagesController#home","StaticPagesController#help",
  "StaticPagesController#about","StaticPagesController#contact",
  "UsersController#new", "UsersController#show", "UsersController#create",
  "UsersController#edit", "UsersController#index", "UsersController#update",
  "ApplicationController#change_language", "SessionsController#destroy",
  "SessionsController#create", "PasswordResetsController#create",
  "PasswordResetsController#after_update_pass", "UsersController#after_save",
  "RelationshipsController#after_follow",
  "RelationshipsController#after_unfollow"
  ],
  ignored_files: []
}
RemoveUnusedMethodsInHelpersCheck: {
  except_methods: ["SessionsHelper#logged_in_user"]}
RemoveUnusedMethodsInModelsCheck: {
  except_methods: ["User#digest"],
  ignored_files: []
}
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
ReplaceInstanceVariableWithLocalVariableCheck: { }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseQueryAttributeCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
