model:
  user:
    user_name:
      max_length: 50
    email:
      max_length: 255
    pass:
      min_length: 6
    pass_reset_expired: 2
  micropost:
    conten:
      max_length: 140
    picture_size:
      max_size: 5
helper:
  user:
    gravatar_size: 80
controller:
  users:
    user_per_page: 15
views:
  users:
    user:
      gravatar_size: 50
  micropost:
    micropost:
      gravatar_size: 50
  shared:
    user_info:
      gravatar_size: 50
