model:
  user:
    user_name:
      max_length: 50
    email:
      max_length: 255
    pass:
      min_length: 6
helper:
  user:
    gravatar_size: 80
controller:
  users:
    user_per_page: 15
views:
  users:
    user:
      gravatar_size: 50

